#!/bin/sh
#
#  Copyright (c) 2000 antifork.org
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
#

PROGRAM=`cat INFO | awk '{print $1}'` 
VERSION=`cat VERSION`
MACHINE=`./config.guess`
AUTHOR=`cat INFO | awk '{print $2}'`
MAIL=`cat INFO | awk '{print $3}'`

echo  
echo  "%"
echo  "% Making program: $PROGRAM $VERSION "
echo  "% machine type  : $MACHINE" 
echo  "%"
echo  "% Copyright (c) 2000 $AUTHOR $MAIL"
echo  "%"
echo  "% Before reporting a bug, please try to reproduce it."
echo  "%"
echo 
